// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WQYQPOOOkQPO'#CeOOQO'#Cj'#CjOOQO'#Cf'#CfQYQPOOOOQO,59P,59POrQPO,59POOQO-E6d-E6dOOQO1G.k1G.k",
  stateData: "!O~O]OSPOS~ORQOSQOTQOUQOWPO~OVTO~PYOVWO~PYOUSRS~",
  goto: "v_PPPPPPPPP`fPPPpXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ LineComment Program Identifier Number String Boolean ) ( Application",
  maxTerm: 14,
  nodeProps: [
    ["openedBy", 7,"("],
    ["closedBy", 8,")"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: ")X~R^pq}rs!Vst#sxy$[yz$a}!O$f!Q![$z!c!}$f#R#S$f#T#Y$f#Y#Z%b#Z#h$f#h#i(R#i#o$f~!SP]~pq}~!YVOr!Vrs!os#O!V#O#P!t#P;'S!V;'S;=`#m<%lO!V~!tOT~~!wRO;'S!V;'S;=`#Q;=`O!V~#TWOr!Vrs!os#O!V#O#P!t#P;'S!V;'S;=`#m;=`<%l!V<%lO!V~#pP;=`<%l!V~#xSP~OY#sZ;'S#s;'S;=`$U<%lO#s~$XP;=`<%l#s~$aOW~~$fOV~~$kTR~}!O$f!Q![$f!c!}$f#R#S$f#T#o$f~%RTS~R~}!O$f!Q![$z!c!}$f#R#S$f#T#o$f~%gUR~}!O$f!Q![$f!c!}$f#R#S$f#T#U%y#U#o$f~&OVR~}!O$f!Q![$f!c!}$f#R#S$f#T#`$f#`#a&e#a#o$f~&jVR~}!O$f!Q![$f!c!}$f#R#S$f#T#g$f#g#h'P#h#o$f~'UVR~}!O$f!Q![$f!c!}$f#R#S$f#T#X$f#X#Y'k#Y#o$f~'rTU~R~}!O$f!Q![$f!c!}$f#R#S$f#T#o$f~(WVR~}!O$f!Q![$f!c!}$f#R#S$f#T#f$f#f#g(m#g#o$f~(rVR~}!O$f!Q![$f!c!}$f#R#S$f#T#i$f#i#j'P#j#o$f",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 41
})
