// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#YQYQPOOOwQPO'#CgO!OQPO'#CjO!VQPO'#CmOOQO'#Cr'#CrOOQO'#Cn'#CnQYQPOOOOQO,59R,59RO!^QPO,59ROOQO,59U,59UO!eQPO,59UOOQO,59X,59XO!lQPO,59XOOQO-E6l-E6lOOQO1G.m1G.mOOQO1G.p1G.pOOQO1G.s1G.s",
  stateData: "!z~OeOSPOS~ORSOSSOTSOUSOVSOWSOYPO]QO`RO~OXVO~PYO[XO~PYO_ZO~PYOX^O~PYO[_O~PYO_`O~PYOWURSTR~",
  goto: "!`gPPPPPPPPPPPhPPhPPhrPPP!UaSOPQRUWY[QUOQWPQYQQ[RX]UWY[aTOPQRUWY[",
  nodeNames: "⚠ LineComment Program Keyword TypeName Identifier Number String Boolean ) ( Parens } { Braces ] [ Brackets",
  maxTerm: 22,
  nodeProps: [
    ["openedBy", 9,"(",12,"{",15,"["],
    ["closedBy", 10,")",13,"}",16,"]"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "3V~Rgpq!jrs!rst$`xy$wyz$|!Q![%R!c!}%w!}#O&[#P#Q&a#R#S%f#T#X%f#X#Y&f#Y#Z+P#Z#]%f#]#^-a#^#`%f#`#a.a#a#b0O#b#h%f#h#i1{#i#o%f#o#p2{#q#r3Q~!oPe~pq!j~!uVOr!rrs#[s#O!r#O#P#a#P;'S!r;'S;=`$Y<%lO!r~#aOV~~#dRO;'S!r;'S;=`#m;=`O!r~#pWOr!rrs#[s#O!r#O#P#a#P;'S!r;'S;=`$Y;=`<%l!r<%lO!r~$]P;=`<%l!r~$eSP~OY$`Z;'S$`;'S;=`$q<%lO$`~$tP;=`<%l$`~$|OY~~%ROX~~%YSU~T~!Q![%R!c!}%f#R#S%f#T#o%f~%kST~!Q![%f!c!}%f#R#S%f#T#o%f~&OSS~T~!Q![%w!c!}%w#R#S%w#T#o%w~&aO`~~&fO_~~&kUT~!Q![%f!c!}%f#R#S%f#T#l%f#l#m&}#m#o%f~'SWT~!Q![%f!c!}%f#R#S%f#T#d%f#d#e'l#e#h%f#h#i)h#i#o%f~'qUT~!Q![%f!c!}%f#R#S%f#T#c%f#c#d(T#d#o%f~(YUT~!Q![%f!c!}%f#R#S%f#T#f%f#f#g(l#g#o%f~(qUT~!Q![%f!c!}%f#R#S%f#T#h%f#h#i)T#i#o%f~)[SR~T~!Q![%f!c!}%f#R#S%f#T#o%f~)mUT~!Q![%f!c!}%f#R#S%f#T#X%f#X#Y*P#Y#o%f~*UUT~!Q![%f!c!}%f#R#S%f#T#b%f#b#c*h#c#o%f~*mUT~!Q![%f!c!}%f#R#S%f#T#W%f#W#X)T#X#o%f~+UTT~!Q![%f!c!}%f#R#S%f#T#U+e#U#o%f~+jUT~!Q![%f!c!}%f#R#S%f#T#`%f#`#a+|#a#o%f~,RUT~!Q![%f!c!}%f#R#S%f#T#g%f#g#h,e#h#o%f~,jUT~!Q![%f!c!}%f#R#S%f#T#X%f#X#Y,|#Y#o%f~-TSW~T~!Q![%f!c!}%f#R#S%f#T#o%f~-fUT~!Q![%f!c!}%f#R#S%f#T#a%f#a#b-x#b#o%f~-}UT~!Q![%f!c!}%f#R#S%f#T#d%f#d#e'l#e#o%f~.fWT~!Q![%f!c!}%f#R#S%f#T#X%f#X#Y(l#Y#c%f#c#d/O#d#o%f~/TUT~!Q![%f!c!}%f#R#S%f#T#c%f#c#d/g#d#o%f~/lUT~!Q![%f!c!}%f#R#S%f#T#d%f#d#e)T#e#o%f~0TTT~!Q![%f!c!}%f#R#S%f#T#U0d#U#o%f~0iUT~!Q![%f!c!}%f#R#S%f#T#h%f#h#i0{#i#o%f~1QUT~!Q![%f!c!}%f#R#S%f#T#V%f#V#W1d#W#o%f~1iUT~!Q![%f!c!}%f#R#S%f#T#[%f#[#])T#]#o%f~2QUT~!Q![%f!c!}%f#R#S%f#T#f%f#f#g2d#g#o%f~2iUT~!Q![%f!c!}%f#R#S%f#T#i%f#i#j,e#j#o%f~3QO]~~3VO[~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 81
})
