// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Keyword = 3,
  TypeName = 4,
  Identifier = 5,
  Number = 6,
  String = 7,
  Boolean = 8
