// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  TypeName = 3,
  Identifier = 4,
  Number = 5,
  String = 6,
  Boolean = 7
