// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WQYQPOOOkQPO'#CeOOQO'#Cj'#CjOOQO'#Cf'#CfQYQPOOOOQO,59P,59POrQPO,59POOQO-E6d-E6dOOQO1G.k1G.k",
  stateData: "!O~O]OSPOS~ORQOSQOTQOUQOWPO~OVTO~PYOVWO~PYOUSRS~",
  goto: "v_PPPPPPPPP`fPPPpXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ LineComment Program Identifier Number String Boolean ) ( Application",
  maxTerm: 14,
  nodeProps: [
    ["openedBy", 7,"("],
    ["closedBy", 8,")"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%k~RXpqnrsvst#dxy#{yz$Q!Q![$V!c!}$_#Y#Z$p#h#i%_~sP]~pqn~yVOrvrs!`s#Ov#O#P!e#P;'Sv;'S;=`#^<%lOv~!eOT~~!hRO;'Sv;'S;=`!q;=`Ov~!tWOrvrs!`s#Ov#O#P!e#P;'Sv;'S;=`#^;=`<%lv<%lOv~#aP;=`<%lv~#iSP~OY#dZ;'S#d;'S;=`#u<%lO#d~#xP;=`<%l#d~$QOW~~$VOV~~$[PS~!Q![$V~$dSR~!Q![$_!c!}$_#R#S$_#T#o$_~$sP#T#U$v~$yP#`#a$|~%PP#g#h%S~%VP#X#Y%Y~%_OU~~%bP#f#g%e~%hP#i#j%S",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 41
})
