// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#YQYQPOOOtQPO'#CfO{QPO'#CiO!SQPO'#CjOOQO'#Co'#CoOOQO'#Ck'#CkQYQPOOOOQO,59Q,59QO!ZQPO,59QOOQO,59T,59TO!bQPO,59TOOQO,59U,59UO!iQPO,59UOOQO-E6i-E6iOOQO1G.l1G.lOOQO1G.o1G.oOOQO1G.p1G.p",
  stateData: "!v~ObOSPOS~ORSOSSOTSOUSOVSOXPO[QOeRO~OWVO~PYOZXO~PYOdZO~PYOW^O~PYOZ_O~PYOd`O~PYOVTRSR~",
  goto: "!]dPPPPPPPPPPePPeeoPPP!RaSOPQRUWY[QUOQWPQYQQ[RX]UWY[aTOPQRUWY[",
  nodeNames: "⚠ LineComment Program TypeName Identifier Number String Boolean ) ( Parens } { Block Array",
  maxTerm: 21,
  nodeProps: [
    ["openedBy", 8,"(",11,"{"],
    ["closedBy", 9,")",12,"}"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: ")n~Rapq!Wrs!`st#|xy$eyz$j!Q![$o!c!}%e!}#O%x#P#Q%}#R#S%S#T#Y%S#Y#Z&S#Z#h%S#h#i(d#i#o%S#o#p)d#q#r)i~!]Pb~pq!W~!cVOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v<%lO!`~!}OU~~#QRO;'S!`;'S;=`#Z;=`O!`~#^WOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v;=`<%l!`<%lO!`~#yP;=`<%l!`~$RSP~OY#|Z;'S#|;'S;=`$_<%lO#|~$bP;=`<%l#|~$jOX~~$oOW~~$vST~S~!Q![$o!c!}%S#R#S%S#T#o%S~%XSS~!Q![%S!c!}%S#R#S%S#T#o%S~%lSR~S~!Q![%e!c!}%e#R#S%e#T#o%e~%}Oe~~&SOd~~&XTS~!Q![%S!c!}%S#R#S%S#T#U&h#U#o%S~&mUS~!Q![%S!c!}%S#R#S%S#T#`%S#`#a'P#a#o%S~'UUS~!Q![%S!c!}%S#R#S%S#T#g%S#g#h'h#h#o%S~'mUS~!Q![%S!c!}%S#R#S%S#T#X%S#X#Y(P#Y#o%S~(WSV~S~!Q![%S!c!}%S#R#S%S#T#o%S~(iUS~!Q![%S!c!}%S#R#S%S#T#f%S#f#g({#g#o%S~)QUS~!Q![%S!c!}%S#R#S%S#T#i%S#i#j'h#j#o%S~)iO[~~)nOZ~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 78
})
